### ISSUE TITLE
[question]: What's the simplest way to create a notification using a custom icon?

### ISSUE THREAD

**Issue by iAmWillShepherd** [OneSignal/node-onesignal#18]
### How can we help?

Notifications created using this client have the OneSignal notification bell as the default icon. It seems possible to specify a custom icon, but it's unclear if people need to set every `*icon` property.

###### The types have 10 properties to set.  
https://github.com/OneSignal/node-onesignal/blob/3b399a35a7b625295ea3f46088b7a7af7f65dbce/models/Notification.ts#L260-L299

Is there a way to specify the icon once?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
the node api library is just a sort of client wrapper for the REST API so it should be the same as the REST API. those params are optional and depend on the application being used. e.g: the hauwei icon params are used for targeting huawei devices, chrome icons for web, etc... (edited) 
+1
thumbsupparrot
ack





[12:27](https://onesignal.slack.com/archives/D013VGKQTDG/p1657049240075109)
the value is the filename of the image
[12:27](https://onesignal.slack.com/archives/D013VGKQTDG/p1657049263116019)
and client/app side, it is expected the file would reside in a specific path
[12:27](https://onesignal.slack.com/archives/D013VGKQTDG/p1657049267396349)
https://documentation.onesignal.com/docs/customize-notification-icons
[12:29](https://onesignal.slack.com/archives/D013VGKQTDG/p1657049356206109)
I don't believe we have a way to specify the icon once for all platforms
[12:31](https://onesignal.slack.com/archives/D013VGKQTDG/p1657049465562149)
the closest thing I can think of is uploading the icon in the notification editor via the dashboard

**Comment by kesheshyan** [comment]
Closing this out for now.
