### ISSUE TITLE
require won't find the module

### ISSUE THREAD

**Issue by rborn** [OneSignal/node-onesignal#5]
Hi, 
I'm trying to use this module with firebase functions (using require) and I get  this error:

`Cannot find module [__edited__]/monorepo/node_modules/@onesignal/node-onesignal/dist/index.js'. Please verify that the package.json has a valid "main" entry`

I believe is because you added `dist` in `.gitignore`? 

Thank you.

**Comment by rgomezp** [comment]
The problem wasn't with the .gitignore but rather a missing .npmignore. Please upgrade to the latest beta4 for the fix.

Thanks for your patience and help.
