### ISSUE TITLE
REST API create notification returns 403 Forbidden error with Cloudflare Recaptcha html

### ISSUE THREAD

**Issue by MuhammadUmarZahid** [OneSignal/node-onesignal#8]
# Description
This is the link to my sample code repo
[https://github.com/MuhammadUmarZahid/one-signal-node](url)

I am trying to send OneSignal notifications from the node project using REST API provided by OneSignal. 
Everything seemed to be working till yesterday. All of sudden today the endpoint:
 
**/api/v1/notifications**

 started returning in response: 

**{
  status: 403,
  statusText: 'Forbidden',
  data: <html>...</html>
.....
}**

The **data** key in the response had **cloudflare** html page which shows **recaptcha**. I dont know how should i solve the recaptcha on the server without opening a browser.

The same error started popping in my android app registered against the same app id on the onesignal dashboard. 

Please help me with this as i want to go into production asap,

# Steps to Reproduce

Unknown but maybe i sent more requests to the onesignal server in the past 2 to 3 days which caused the cloudflare ddos protection to trigger. 

# Environment
node version 16.4.0
npm version 7.18.1
Visual Studio Code 1.64.1
Axios 0.25.0

**Comment by jkasten2** [comment]
@MuhammadUmarZahid Thanks for reporting. I would checkout Cloudflare's Captchas documentation on why this could be happening to you:
https://support.cloudflare.com/hc/en-us/articles/200170136-Understanding-Cloudflare-Captchas-Managed-Challenge-and-Challenge-Passage

I would review steps there, report back here on each one of the steps, and reach out to OneSignal as well to confirm the rules on their end.

**Comment by rgomezp** [comment]
Closing due to no response.
